@BlablablaBlog.Server_HostAddress = https://localhost:7129

GET {{BlablablaBlog.Server_HostAddress}}/post/
Accept: application/json
###
POST {{BlablablaBlog.Server_HostAddress}}/post/
Accept: application/json
Content-Type: application/json
 {
   "title": "заголовок сообщения",
   "message": "текст сообщения",
   "authorId": 1,
   "tags":[{"text":"tag1"},{"text": "tag2"},{"text": "tag3"} ]
 }
###
DELETE {{BlablablaBlog.Server_HostAddress}}/post/1
###
GET {{BlablablaBlog.Server_HostAddress}}/user/
Accept: application/json
###
GET {{BlablablaBlog.Server_HostAddress}}/feed

###
